### ISSUE TITLE
Delete all user data when the user is deleted

### ISSUE THREAD

**Issue by NikhilM98** [llaske/sugarizer-server#109]
When a user is deleted, his journals and stats are not removed from the database.
I was wondering whether should we remove the user data when the user is deleted. The data can be useful for analytics when we expand sugarizer-server dashboard. But storing someone's data without their consent is also not good.

**Comment by llaske** [comment]
Good point.
I don't think we need to remove stats but journal should certainly be removed.

**Comment by NikhilM98** [comment]
@llaske okay. I'll start working on it 🙂

**Comment by NikhilM98** [comment]
Fixed in #115
