### ISSUE TITLE
Search for users in journal screen is limited

### ISSUE THREAD

**Issue by ashish0910** [llaske/sugarizer-server#111]
On `dashboard/journal?lang=en` route when you click on select user option it shows only 10 most recent users and not others and when you search the user which is left then it shows no result found . Hence we are not able to access journal of all users . 

as you can see user 'b' exists 

![Screenshot 2019-03-17 at 8 37 09 AM](https://user-images.githubusercontent.com/30404493/54484593-f6d22080-488f-11e9-8a79-4195d5a32a40.png)

On journal page on searching 'b' , it shows no result found

![Screenshot 2019-03-17 at 8 37 32 AM](https://user-images.githubusercontent.com/30404493/54484601-19fcd000-4890-11e9-868d-f9c619b167e7.png)

I have started working on this issue

**Comment by llaske** [comment]
You're right. It could be improve.

**Comment by ashish0910** [comment]
@llaske that did not work in my case 

![journal](https://user-images.githubusercontent.com/30404493/55642871-4f417180-57ef-11e9-8b57-a43e78d64253.gif)

Also there is another issue in it , when you go to users page and click on show journal icon for a user who is not in the list of the most ten recent users then it shows the name of most recent user but shows the desired data that is the of the user selected .

![journal2](https://user-images.githubusercontent.com/30404493/55643237-4dc47900-57f0-11e9-8701-62cfe51bfccf.gif)

**Comment by NikhilM98** [comment]
Fixed in #213
