### ISSUE TITLE
No message when searched activity is not found

### ISSUE THREAD

**Issue by Anshuman71** [llaske/sugarizer-server#112]
When we miss a search in activities we are not shown any message regarding the `no match found` which seems odd and is not quite a good user experience.
I have fixed this in #125

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/125

**Comment by Anshuman71** [comment]
thanks, @llaske for reviewing. I am closing this issue now.

**Comment by llaske** [comment]
I don't close issues before releasing a new version.

**Comment by NikhilM98** [comment]
@llaske I've also closed some of my issues. Please check if there's a need to reopen those issues.
