### ISSUE TITLE
`How users are launching activities` not showing any data

### ISSUE THREAD

**Issue by Anshuman71** [llaske/sugarizer-server#119]
Is this only me or the statistics page is not showing a chart for `How users are launching activities` when there is indeed an entry in the database collection 'stats'
![Screenshot from 2019-03-18 09-46-39](https://user-images.githubusercontent.com/28081510/54506555-f6568a00-4962-11e9-971d-945a8b93d0f8.png)

I am on this issue and have found the bug.
Please let me know if this is an issue indeed

**Comment by ashish0910** [comment]
@Anshuman71 I don't think it is an issue 
![Screenshot 2019-03-18 at 9 52 01 AM](https://user-images.githubusercontent.com/30404493/54506707-c65bb680-4963-11e9-9a55-135308542190.png)

when you login and launch activities from here `http://127.0.0.1:8080/` then you generate stats for it

**Comment by Anshuman71** [comment]
@ashish0910 but in the database, we have entry regarding the 'launch_activity', 'relaunch_activity' still it's not showing

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/commit/c29eeaa457d1953f386ed0329c94455f2d1fd70c
