### ISSUE TITLE
Add models for database

### ISSUE THREAD

**Issue by Anshuman71** [llaske/sugarizer-server#126]
Add models/schema for database collections just a [reference](https://github.com/Anshuman71/CRUD-using-MongoDB-and-Express-).
This is just to take an opinion on this particular thought.

**Comment by NikhilM98** [comment]
Yes, we've faced issues due to missing validation before. I recommended using Mongoose [here](https://github.com/llaske/sugarizer-server/issues/56), but the idea didn't get approved.

**Comment by NikhilM98** [comment]
Suggestion: If we're not ready for Mongoose ODM yet, then maybe we can use custom MongoDB [schema validation](https://docs.mongodb.com/manual/core/schema-validation/). But that'll also require plenty of changes and testing in the controllers.

**Comment by llaske** [comment]
I think that the API Documentation is sufficient today.
