### ISSUE TITLE
main.js:66 Uncaught TypeError: Cannot read property 'server' of null

### ISSUE THREAD

**Issue by Anshuman71** [llaske/sugarizer-server#130]
![two](https://user-images.githubusercontent.com/28081510/54620233-db336980-4a8b-11e9-812f-c491a0b182ef.gif)
i fixed this issue was just a one condition,

**Comment by NikhilM98** [comment]
I've already referenced and fixed this issue here #129

**Comment by Anshuman71** [comment]
@NikhilM98  thanks for the followup I am closing this issue

**Comment by NikhilM98** [comment]
@Anshuman71 the PR is not yet merged :sweat_smile:. I think it'd be good if we wait for the PR to be merged before closing this issue.

**Comment by NikhilM98** [comment]
Fixed in #129
