### ISSUE TITLE
Inconsistency in the function execution

### ISSUE THREAD

**Issue by NikhilM98** [llaske/sugarizer-server#139]
In the `process-results` function in `api/controller/activities`.

The variables for the array `activities2` and the flag `isValid` are defined as global variables.
Since JS is asynchronous in nature and so is Node, this can lead to inconsistency in the array and flags in the case the function is executed at the same time by two or more users (If the flag is raised for one user, it will also be raised for the second user. It's also possible that the array will end up returning the same value for parallel executions)

This bug has a slight possibility of being detected in case of a few users, but for the long term, it's better if it's resolved.

https://github.com/llaske/sugarizer-server/blob/2cf2d524055323ded375a310ba4259aadde5ee9f/api/controller/activities.js#L230-L237

https://github.com/llaske/sugarizer-server/blob/2cf2d524055323ded375a310ba4259aadde5ee9f/api/controller/activities.js#L252-L256

For now, it seems like a minor issue. Should I fix this?

**Comment by Anshuman71** [comment]
> 
> 
> In the `process-results` function in `api/controller/activities`.
> 
> The variables for the array `activities2` and the flag `isValid` are defined as global variables.
> Since JS is asynchronous in nature and so is Node, this can lead to inconsistency in the array and flags in the case the function is executed at the same time by two or more users (If the flag is raised for one user, it will also be raised for the second user. It's also possible that the array will end up returning the same value for parallel executions)
> 
> This bug has a slight possibility of being detected in case of a few users, but for the long term, it's better if it's resolved.
> 
> [sugarizer-server/api/controller/activities.js](https://github.com/llaske/sugarizer-server/blob/2cf2d524055323ded375a310ba4259aadde5ee9f/api/controller/activities.js#L230-L237)
> 
> Lines 230 to 237 in [2cf2d52](/llaske/sugarizer-server/commit/2cf2d524055323ded375a310ba4259aadde5ee9f)
>  function process_results(req, activities) { 
>   
>  	//duplicate activities 
>  	activities2 = []; 
>   
>  	//add options first for filtering 
>  	var opt = {}; 
>  	opt = addOptions('name', req.query, opt); 
> 
> [sugarizer-server/api/controller/activities.js](https://github.com/llaske/sugarizer-server/blob/2cf2d524055323ded375a310ba4259aadde5ee9f/api/controller/activities.js#L252-L256)
> 
> Lines 252 to 256 in [2cf2d52](/llaske/sugarizer-server/commit/2cf2d524055323ded375a310ba4259aadde5ee9f)
>  activities.forEach(function(activity, key) { 
>   
>  	//flag 
>  	isValid = true; 
>   
> 
> For now, it seems like a minor issue. Should I fix this?

@NikhilM98  yes, this should be fixed. I also think it would lead to some bugs in a race condition(multiple users). Global variables also reflect an inconsistent codebase. 
Personal opinion

**Comment by NikhilM98** [comment]
@Anshuman71 thanks for the quick feedback. I've created a PR handling the global variable affecting the race case scenario.

**Comment by NikhilM98** [comment]
Fixed in #140
