### ISSUE TITLE
Page navigation problem on language switching 

### ISSUE THREAD

**Issue by ashish0910** [llaske/sugarizer-server#142]
After switching the language the reload takes place and forgets the query of the user and redirects to default situation which is not good .

Example :

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30404493/54878362-8019c200-4e51-11e9-8d63-45252bcc4ff1.gif) 

Similar behaviour takes place in case of journal also .

**Comment by ashish0910** [comment]
I have started working on this issue .

**Comment by NikhilM98** [comment]
I think this is the expected result. Retaining the query data can give rise to unexpected bugs.

**Comment by ashish0910** [comment]
@NikhilM98 I don't think it is a good idea . It will have a very bad impact on user experience . for example if you have set 3-4 parameters such as name , sort and classroom and then you change the language , it will delete all the queries and will show default result and then user will have to set all those parameters . @llaske what are your views on it ?

**Comment by NikhilM98** [comment]
@ashish0910 To fix this, you've to check the query string on language change, search for the language parameter in the string, and adjust it accordingly retaining the other parameters.
But this will cause the user to make the GET request twice on the route with the same parameters. This may have undesirable consequences in certain cases. This may also lead to other bugs in the future.

**Comment by NikhilM98** [comment]
I cannot locate this issue in the Journal View. Can you please upload the screenshot?

**Comment by ashish0910** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30404493/54879214-5ca84480-4e5c-11e9-8dee-59b76e51388b.gif)

**Comment by ashish0910** [comment]
> @ashish0910 To fix this, you've to check the query string on language change, search for the language parameter in the string, and adjust it accordingly retaining the other parameters.
> But this will cause the user to make the GET request twice on the route with the same parameters. This may have undesirable consequences in certain cases. This may also lead to other bugs in the future.

@NikhilM98 we might need some other way to handle this issue .

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/242
