### ISSUE TITLE
Sugarizer logo not visible in dashboard on users menu

### ISSUE THREAD

**Issue by yog24esh** [llaske/sugarizer-server#147]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/16835166/54967526-a0ef2e00-4f9d-11e9-917f-875e075ec9a3.gif)

On sugar-server dashboard (master branch) on opening a new user page , the sugar label text is missing on top left.

**Comment by llaske** [comment]
You're right but it seems fixed on dev branch.

**Comment by harshbawari** [comment]
Hello, is the bug still open to fix or someone already fixed it? I am new to open source and I want to just look at what I can do with it.
