### ISSUE TITLE
Word "users" use instead of "students" on the dashboard

### ISSUE THREAD

**Issue by NikhilM98** [llaske/sugarizer-server#148]
On the dashboard, the card shows that there are 5 users.
![Screenshot from 2019-03-26 17-19-02](https://user-images.githubusercontent.com/24666770/54995169-226dad00-4fec-11e9-978d-8d5a91d50919.png)

But actually, there are 9 users consisting of 5 students and 4 admins.
![Screenshot from 2019-03-26 17-26-05](https://user-images.githubusercontent.com/24666770/54995298-6e205680-4fec-11e9-8f1a-677695c53944.png)
![Screenshot from 2019-03-26 17-26-14](https://user-images.githubusercontent.com/24666770/54995303-6fea1a00-4fec-11e9-9224-7ac42fb8837d.png)

When you click on "View all users", it takes you to users page, listing all the students.

This is a minor language issue. Should we replace strings like "Users" and "View all users" with "Students" and "View all students"?

**Comment by ashish0910** [comment]
@NikhilM98 here view all users should mean for teachers and students not admin . Since teacher API is not built as of now view all users leading to students should be expected behavior . View all users feels correct as of now but when teacher will included then view all students and view all teachers will make sense .

**Comment by NikhilM98** [comment]
`Students` still seem more correct.
Let's wait for the feedback from other contributors. What do you think @Anshuman71 @SomtochiAma?

**Comment by Anshuman71** [comment]
@NikhilM98, yes I also think it should show what it is. So >Students seems to be the key here. @ashish0910, Teachers API is not yet built but it is to be build and In my opinion, it won't affect the things are working and will work. 
Please, give your thoughts on that.

**Comment by SomtochiAma** [comment]
I agree with @NikhilM98  on this. It is a small UX issue to avoid confusion, Students is much better.

**Comment by llaske** [comment]
Yes it's true it should be "students" instead of "users".
