### ISSUE TITLE
Language doesn't switch on mobile view

### ISSUE THREAD

**Issue by SomtochiAma** [llaske/sugarizer-server#154]
The language selection doesn't work on the mobile view

Steps to replicate
1. Go to the dashboard home and make it responsive with chrome dev tools

2. Try switching the languages from the toggleable nav bar
![Screenshot (39)](https://user-images.githubusercontent.com/34774756/55124529-c6e41200-5106-11e9-814d-c0fedfd26042.png)

**Comment by NikhilM98** [comment]
Fixed in #155
