### ISSUE TITLE
Project Not Running 

### ISSUE THREAD

**Issue by vaarigupta** [llaske/sugarizer-server#163]
I want to run sugarizer-server via the instructions given in the documentation but I got stuck with the following error and cannot resolve it. Please help me out to run the project on http://127.0.0.1:8080/

![issue](https://user-images.githubusercontent.com/32798276/55425763-d6e57100-55a0-11e9-8af1-2ed89a0b3d28.png)

What can I do? 
I used 
`sudo npm  uninstall fibers`

then

`sudo npm install fibers`

but still not working

**Comment by NikhilM98** [comment]
@vaarigupta 
Checkout to `dev` branch. `npm install` -> `npm start`

**Comment by vaarigupta** [comment]
hey I did the same but still could not run and it is showing another error
I have checked out branch to dev and then did 

`npm install`

![error1](https://user-images.githubusercontent.com/32798276/55500294-a9163000-5665-11e9-949d-aac778c2087d.png)

**Comment by NikhilM98** [comment]
@vaarigupta You need to clone [Sugarizer](https://github.com/llaske/sugarizer) repository in the same parent folder (GSOC folder in your case). Then `cd` to `sugarizer` and run `npm install`.

I once wrote a setup script for Sugarizer-Server, though it was never merged. You can view the script for hints [here](https://github.com/NikhilM98/sugarizer-server/blob/e1fb1bf963b5d1c7843ca83807e5e7b4e31306e1/setup.sh)

**Comment by ashish0910** [comment]
> @vaarigupta You need to clone [Sugarizer](https://github.com/llaske/sugarizer) repository in the same parent folder (GSOC folder in your case). Then `cd` to `sugarizer` and run `npm install`.
> 
> I once wrote a setup script for Sugarizer-Server, though it was never merged. You can view the script for hints [here](https://github.com/NikhilM98/sugarizer-server/blob/e1fb1bf963b5d1c7843ca83807e5e7b4e31306e1/setup.sh)

Yes but you don't need to run npm install in sugarizer folder unless you want to run it on electron

**Comment by vaarigupta** [comment]
> @vaarigupta You need to clone [Sugarizer](https://github.com/llaske/sugarizer) repository in the same parent folder (GSOC folder in your case).
> 
> I once wrote a setup script for Sugarizer-Server, though it was never merged. You can view the script for hints [here](https://github.com/NikhilM98/sugarizer-server/blob/e1fb1bf963b5d1c7843ca83807e5e7b4e31306e1/setup.sh)

hey I have already done that still not working

![gsoc1](https://user-images.githubusercontent.com/32798276/55578311-38d5e000-5733-11e9-9ccf-0dabb3c09cb0.png)

**Comment by llaske** [comment]
Which version of nodejs are you using?

**Comment by vaarigupta** [comment]
> Which version of nodejs are you using?

I am using version 8 - v8.15.1

**Comment by NikhilM98** [comment]
@vaarigupta can you log some variables out?

Insert some `console.log` statements in this code and share the log?
https://github.com/llaske/sugarizer-server/blob/41278307ededd620d7f7e85fbbcfd9a1b0197a7a/api/controller/activities.js#L43-L51

![Screenshot from 2019-04-05 15-26-50](https://user-images.githubusercontent.com/24666770/55620306-349fd600-57b8-11e9-8216-f14d0d79fb90.png)

I guess there's either some issue with the path of some `.ini` file or some `.ini` file is not being parsed correctly. Logging would help pinpoint the issue.

Also, can you check that your Sugarizer folder is not modified and is up-to-date with upstream?

**Comment by vaarigupta** [comment]
> @vaarigupta can you log some variables out?
> 
> Insert some `console.log` statements in this code and share the log?
> [sugarizer-server/api/controller/activities.js](https://github.com/llaske/sugarizer-server/blob/41278307ededd620d7f7e85fbbcfd9a1b0197a7a/api/controller/activities.js#L43-L51)
> 
> Lines 43 to 51 in [4127830](/llaske/sugarizer-server/commit/41278307ededd620d7f7e85fbbcfd9a1b0197a7a)
> 
>  if (stats.isDirectory()) { 
>  	// Read the activity.info file 
>  	var stream = fs.createReadStream(activitiesPath + path.sep + file + path.sep + activityInfoPath, { 
>  		encoding: 'utf8' 
>  	}); 
>  	stream.on('data', function(content) { 
>  		// Parse the file as an .INI file 
>  		var info = ini.parse(content); 
>   
> ![Screenshot from 2019-04-05 15-26-50](https://user-images.githubusercontent.com/24666770/55620306-349fd600-57b8-11e9-8216-f14d0d79fb90.png)
> 
> I guess there's either some issue with the path of some `.ini` file or some `.ini` file is not being parsed correctly. Logging would help pinpoint the issue.
> 
> Also, can you check that your Sugarizer folder is not modified and is up-to-date with upstream?

Thanks for your suggestion , I will try to implement this one

**Comment by vaarigupta** [comment]
@NikhilM98  thanks buddy , now its running fine. I think there was some issue with syncing with the repository.
I  checked out to dev branch and run 
`sudo service mongod start`
`node sugarizer`
Now its working fine

![workingfine](https://user-images.githubusercontent.com/32798276/55674495-301c1000-58d3-11e9-8099-969684f8970a.png)
I did not have to write log statements.
Thanks for all the support 
#opensource_is_great_learning
