### ISSUE TITLE
Use a random color for new user/classroom created from dashboard

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#166]
When a new user/classroom is created, the default color stroke/fill is always the same (the fist color in the selection list), it will be better to propose a random color like for new user creation in Sugarizer App.

![Capture d’écran de 2019-04-10 17-02-44](https://user-images.githubusercontent.com/981841/55890295-c0e43b80-5bb2-11e9-89bf-76e46cd59892.png)

**Comment by ashish0910** [comment]
I have started working on this issue

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/167
