### ISSUE TITLE
Can't create a classroom with a space into the dashboard

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#19]
In the dashboard, it's not possible to create a classroom with a space into the dashboard.

**Comment by utkarsh-raj** [comment]
Can you elaborate a bit more about the issue @llaske ?
Is this related to not being able to have an option to create classroom from the server dashboard ?

**Comment by ashish0910** [comment]
sorry @utkarsh-raj I was also working on it . May be you can work on some other issue ?

**Comment by utkarsh-raj** [comment]
Not a problem @ashish1910 , as long as the bugs get lesser :)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/26
