### ISSUE TITLE
Missing message string in dashboard on delete

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#21]
When clicking on the delete button in the classroom a popup message appears but there is no string message.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/981841/52305269-060ea600-2995-11e9-94aa-4cf8391633da.png">

**Comment by ashish0910** [comment]
@llaske I would like to work on it. However i am not able to find classroom option on dashboard .
![screenshot 2019-02-17 at 6 00 13 pm](https://user-images.githubusercontent.com/30404493/52912903-0cc6e280-32de-11e9-8ab3-2154fed5df85.png)

**Comment by llaske** [comment]
You should get the dev branch of the repo. The classroom features is not present in the master branch

**Comment by ashish0910** [comment]
This comes up after clicking on classroom on dashboard.
![screenshot 2019-02-19 at 3 49 20 pm](https://user-images.githubusercontent.com/30404493/53007858-1d05cb80-345e-11e9-993f-55a491126aca.png)

**Comment by ashish0910** [comment]
@llaske please review #24

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/commit/59eaafd4891b63d564b37bc3d532ab24c2e93629
