### ISSUE TITLE
Provide a way to remove multiple users at the same time

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#217]
Currently if an admin want to remove a bunch of users, he has no choice to remove them one by one using the dashboard. It could be a very long process if the number of users is large.
I suggest to add a way, for example using a specific syntax in the import script, to remove multiple users at the same time.

**Comment by NikhilM98** [comment]
Can we add something like: `node scripts/remove_users.js filename.csv`? The CSV will contain the name of the users the admin wants to delete.
It'll generate an output file with info about the users deleted/failed to delete.

**Comment by llaske** [comment]
Will be nice if we could call it from the dashboard. It's why my first thought was to update the import script.

**Comment by NikhilM98** [comment]
@llaske if you want the bulk delete feature to be accessible from the dashboard then maybe we can modify the `Import Users` feature on the dashboard such that if we upload a CSV with user type as `delete` (Current user types are Admin, Student, and Teacher) then the script will find and delete that user.

**Comment by llaske** [comment]
Sounds like a good idea but we need to update the `seed_users.js` script to do the same. So admin could do the action both from the command line and from the UI.

**Comment by NikhilM98** [comment]
Yes. I've already started working on `seed_users.js` before working on the API. I'll try to make a PR for both the scripts by tomorrow.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/218
