### ISSUE TITLE
Shared journal content is incorrect in dashboard

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#219]
In Sugarizer, the shared journal is the place where any user can share content with other users on the server. So, the shared journal content should be the same for any user.

The current shared journal view in the dashboard seems to display only content of shared journal created by the current user. So the shared journal content is not complete and is not the same for all users. 

![2020-01-20 09-53-19 2020-01-20 09_55_04](https://user-images.githubusercontent.com/981841/72712442-5150a300-3b6b-11ea-890f-21f7f1359710.gif)

Plus, it's not pertinent to use a combobox to switch from private journal to shared journal. A checkbox could be enough.

**Comment by NikhilM98** [comment]
@llaske actually, I intentionally added this feature. The goal was to show only the shared journal entries created by that user. 

> In Sugarizer, the shared journal is the place where any user can share content with other users on the server. So, the shared journal content should be the same for any user.

Shared journal are still the same for all the users when accessed from Sugarizer. Sugarizer-Server is an administrator app and this feature is intended to show journal entries corresponding to a user, so it only shows shared journal entries belonging to that user. If you need some way to access all shared entries in one place, then we can add a button to show `All shared entries`.

@tarunsinghal92 you originally created this feature. What's your opinion about it?

**Comment by llaske** [comment]
Hmmm. Interesting.

BTW currently administrators/teachers don't ask for a way to filter shared journal by users.
So I think it's better to provide:
- a way to see private content for a specific user
- a way to see shared content for all users

So I suggest to remove the Private/Shared combo and to replace it by a checkbox "Shared journal".
If the checkbox is unchecked (default), the administrator/teacher could select an user and show journal content when clicking on Show results button.
If the checkbox is checked, the combo to select user will be nullified and in read-only and when clicking on Show results button all shared journal content will be showed.

**Comment by sarthak-g** [comment]
working on this

**Comment by sarthak-g** [comment]
@llaske can you please tell which part of code find entries when "show results" button is pressed?
I'm unable to find it.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/223
