### ISSUE TITLE
Add students icon in dashboard in classroom edit

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#22]
When editing a classroom to change students composition, two lists are displayed. One with the list of students in the classroom, the other with the list of students out of classroom. 

<img width="516" alt="image" src="https://user-images.githubusercontent.com/981841/52443679-aa742200-2b26-11e9-89d6-79dc8b7082e7.png">

The idea is to add the students icon with the student color before the name of each student.

**Comment by utkarsh-raj** [comment]
Working on it. Work required in the icon.js file to change the icon dimension for the option.

**Comment by llaske** [comment]
@utkarsh-raj  Hmmm, interesting. Initially icon.js - which is part of [sugar-web library ](https://github.com/llaske/sugarizer/blob/master/lib/sugar-web/graphics/icon.js)- not mentioned icon size. It's better to try to avoid use hardcoded size inside.

**Comment by ashish0910** [comment]
@utkarsh-raj can I also work on it ?

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/commit/6178212c6e2a014cca2df1b882411a73de7205c0
