### ISSUE TITLE
Add a download icon in Dashboard Journal view

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#220]
The idea is to add a download action icon on each line of the Journal view.

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/981841/72716693-f28f2780-3b72-11ea-9661-ae2e3ab79e59.png">

This icon will allow to download the item and save it locally. This feature is the same than the "Copy to device" feature of the Sugarizer Journal.
Depending of the item mime type, the content will be saved as a JSON, JPG, ODT, PDF, ... file.
See the list of supported datatype [here](https://github.com/llaske/sugarizer/blob/dev/lib/util.js#L436).

**Comment by hqrshguptq** [comment]
Is it done?

**Comment by llaske** [comment]
@hqrshguptq No it's not.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/225
