### ISSUE TITLE
Allow teachers to connect to Sugarizer client

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#222]
Since https://github.com/llaske/sugarizer/commit/9094711b32ab3dd151954f8d2113be801e139683  Sugarizer allow teachers to login to the app.

BTW it doesn't work because when a teacher is created it doesn't have a private journal and a shared journal. See [here](https://github.com/llaske/sugarizer-server/blob/dev/api/controller/users.js#L493). So the login from Sugarizer app works but it's not possible for a teacher to store something in the Journal or to access to the remote/shared journal.

![Peek 26-01-2020 22-11](https://user-images.githubusercontent.com/981841/73141862-e4686c00-4088-11ea-9bd7-2a15a047bb51.gif)

The idea is to update Sugarizer Server to allow a teacher to login to Sugarizer app with a real Journal.
It means change the teacher creation but also the teacher update and delete.
It's important too to add a new test unit handle it.

**Comment by NikhilM98** [comment]
So you just want
- The teacher to login to Sugarizer and access their journal entries.
- Teacher can be created/deleted by the admin only.
- In Sugarizer-Server, add some way to view teacher journal entries.

**Comment by llaske** [comment]
Yes for the two first points. 

> In Sugarizer-Server, add some way to view teacher journal entries.

Interesting I didn't think about that 🤔  I don't think we need to add in the Dashboard a way for a teacher to view its own entries. He could see its entries by connecting to Sugarizer directly.
But, yes, the admin should be able to see Journal entries for teachers too.

**Comment by NikhilM98** [comment]
@llaske in the latest pull request (#224), 
- The admin can view teacher entries just like he views student entries.
- A teacher can view their entry along with the entries of their students. A teacher cannot access the entries of other teachers.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/224
