### ISSUE TITLE
Show the right icon in Dashboard for TXT/ODT/DOC/PDF

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#226]
In the dashboard, when displaying Journal content TXT/ODT/DOC/PDF (all coming from Write activity), a generic icon is displayed.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/981841/74143511-38cc2980-4bfb-11ea-8edb-4b8b6c577d5e.png">

In Sugarizer app, due to [this](https://github.com/llaske/sugarizer/blob/dev/js/journal.js#L229), a specific icon is displayed for these contents.

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/981841/74143655-7a5cd480-4bfb-11ea-892b-f3e81bfd7d16.png">

**Comment by NikhilM98** [comment]
Fixed in [030a3](https://github.com/llaske/sugarizer-server/pull/225/commits/030a33bbdb163673e0c2580d915d243e682ba411).

**Comment by llaske** [comment]
Look like it should be change on the home screen too:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/981841/74231658-5ff02d00-4cc7-11ea-9cab-04019e635532.png">

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/228
