### ISSUE TITLE
Allow opening PDF content in dashboard

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#227]
When trying to open a PDF content in Journal, a message "No linked activity" is displayed. 

![image](https://user-images.githubusercontent.com/981841/74144334-d6742880-4bfc-11ea-9810-fabbc8e32928.png)

It will be better if the document is open in a new window like in Sugarizer app.
The code to do this in Sugarizer app is [here](https://github.com/llaske/sugarizer/blob/dev/js/journal.js#L404).

**Comment by NikhilM98** [comment]
Fixed in [999f46](https://github.com/llaske/sugarizer-server/pull/225/commits/999f46afe5edf111d3b5970e2144114c18c244fd).
