### ISSUE TITLE
Expose presence and server on the same port

### ISSUE THREAD

**Issue by mikklfr** [llaske/sugarizer-server#232]
As of today Sugarizer Server exposes two ports:
- 8080 for the Web service
- 8039 for the Presence service

It would be convenient to have a way to expose only one port and have the client and server to use this one path.

This would simplify the load balancer integration and also would allow to use the service behind proxies which does not allows ports other than 80 and 443.

Having a special path like /presence could be a way to solve the websocket access.

This may be a configuration thing to allow legacy and new versions to work during a transition phase.

**Comment by cperreault** [comment]
I would be interested in working on that. I currently encounter a problem with the Presence service not reachable when behind an Apache proxy. The thing is that I wanted to use an existing virtual machine to deploy a Sugarizer instance (with docker-compose) for the COVID-19 educational continuity on a Linux machine that already host other websites with Apache. I set up the TLS certificate at the Apache level. The HTTPS part works well, but can't connect to the 8039 WebSocket port either when served by Docker or proxied by Apache (I tried many settings). Do you know if I can currently achieve hosting Sugarizer behind Apache + SSL with Presence working or it would require some code change? Thanks

**Comment by mikklfr** [comment]
Hello ! 

It should be possible to do an apache proxy using the actual code. Maybe we can have a look with you and @llaske to solve this and to write some documentation to get something up and running first and share with the community.

Having the same port will surely be better but as far as I know, there's nothing ready for now.

**Comment by llaske** [comment]
@cperreault it should be possible to use an Apache proxy instead of NGinx but I don't have experience about that.
Could you describe what is the issue? Is it only a problem with presence?
Did you set up the SSL options in your env/docker.ini file like mentioned [here](https://github.com/llaske/sugarizer-server/tree/dev#running-server-securely-using-ssl)?

**Comment by cperreault** [comment]
Hi @llaske, I finally got it working by not proxying the Presence service by Apache. I encountered a login problem in the admin panel (/dashboard) to finally figure out that `strict_ssl` must be set to `false` because the Apache proxy is addressing localhost and there was a security error with alias name of the certificate. So my working configuration is to install the SSL certificate at the Docker level, so that both HTTPS and Presence are encrypted. Otherwise, the HTTPS website was trying to establish a secure connection to the Presence service, with wss instead of ws, and it did not work because it was not secured. So finally it work and it is secure! Thanks!

If I go back to the present issue, would there be a legacy issue for current Desktop/Mobile apps or other if the Presence would be running on the same port, but at a dedicated path such as /presence as suggested by @mikklfr?

**Comment by llaske** [comment]
Nice to hear it works now.
BTW on the Sugarizer client side, a change is need to support using the same port and a different URL
All the stuff is done [here](https://github.com/llaske/sugarizer/blob/dev/lib/sugar-web/presence.js#L134).

`that.socket = new WebSocket((secure ? 'wss://' : 'ws://')+server+':'+port);`

This line build the server URL by reading the presence port and the server name. So it's not directly possible to use a different URL for presence today.

**Comment by aitorpazos** [comment]
This is also relevant when running sugarizer in kubernetes as the ingress-controllers doesn't support setting rules for different ports. Being able to route by path on same port as the app/api would be great.

**Comment by llaske** [comment]
@aitorpazos but Sugarizer now works well on Kubernetes. See https://github.com/NikhilM98/sugarizer-chart
I wonder if this fix is still need. @mikklfr @NikhilM98 what do you think?

**Comment by NikhilM98** [comment]
[Kunernetes-Ingress](https://github.com/nginxinc/kubernetes-ingress/) allows setting Custom Ports by simply editing their `values.yaml` file and setting `customPorts`. 

There are other Nginx-Ingress implementations that does not allows this flexibility. Maybe they'll allow setting Custom Ports in future. Meanwhile this Nginx-Ingress controller works best for us.

Also, moving presence on the same port might make Sugarizer Server slower/unstable instead.

**Comment by NikhilM98** [comment]
> Also, moving presence on the same port might make Sugarizer Server slower/unstable instead.

Presence currently runs on different port and has seperate load balancing than Sugarizer Server resources/requests. Most of the data of the presence is stored in the memory and it also requires high availability.

Sugarizer Server requests sometimes take long time to process. If we use same load balancer for both of them then it might cause unexpected issues.

I'm saying this theoretically. I have not tested it. I'll take lot of testing and the current implementation works just fine so I'll avoid testing it for now 😄

**Comment by mikklfr** [comment]
👋  As Nikhil pointed out it works but it's kinda a hack.
In order to go full support for cloud native providers we should move onto standard ports and think about how to achieve high availability for our websockets.

**Comment by llaske** [comment]
I've added support of the same port for web and presence in https://github.com/llaske/sugarizer-server/commit/117994f1cb9a97406905e4f29b92d639b061eaa4
Just use the same value for `web` and `presence` value in the `.ini` file and voila!

I've tested in different settings with HTTP and with HTTPS and it seems to work (no need to upgrade the Sugarizer app side). Please test on your side too.

Note:  It now requires node.js 10+

**Comment by aitorpazos** [comment]
Thanks! Although we I could make it work following the helm chart pointed out by @NikhilM98 , this only works with the support of `VirtualServer` resource provided by nginx inc ingress controller (https://docs.nginx.com/nginx-ingress-controller/), not with the k8s community nginx ingress controller (https://kubernetes.github.io/ingress-nginx/) or haproxy ingress-controller (https://github.com/haproxytech/kubernetes-ingress).
So this is very welcome!! Thanks!

**Comment by mikklfr** [comment]
Well done Lionel! I will try to look at High Availability subjects when I'll have some free time but right now this modification will definitely make it easier!
