### ISSUE TITLE
Activity list doesn't scroll while reordering, causes multiple server calls.

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer-server#235]
The activity list in the Dashboard does not scroll up/down while reordering activities. This leads to multiple drag-and-drops to reorder single activity and each drop causes a POST request to update the list on the server.
Also, there is an unnecessary POST request even when the list order hasn't changed.

![dragScrollIssue](https://user-images.githubusercontent.com/40134655/75979388-69efff00-5f06-11ea-866c-9d023e6fb014.gif)

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/236
