### ISSUE TITLE
Overflow on opening any dropbox

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer-server#238]
Whenever a dropbox is opened, it leads to the body overflowing horizontally.

![dropboxOverflowIssue](https://user-images.githubusercontent.com/40134655/76285601-2a3e6400-62c6-11ea-9362-bdfffe6d27ab.gif)

I'm working on a fix.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/239
