### ISSUE TITLE
Selected option's text isn't localized

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer-server#240]
In the users view, the selected option of the role-selector is never localized after page load.

![selectedLocalizeIssue](https://user-images.githubusercontent.com/40134655/76304224-07717700-62e9-11ea-868d-bfd70dc79bf9.gif)

I'm working on a fix for this.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/commit/ac791858f1f0bb968e280944d36eb235b3a628c4
