### ISSUE TITLE
Add multiple actions to Journal and Users view

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer-server#245]
The entries in the Journal view for a user shows a list with individually dispatch-able actions (Launch/Download/Delete). Wouldn't it be a good feature to have check boxes similar to Sugarizer journal to perform batch operations (mainly download and delete). It would speed up the process of download and deletion. What do you say @llaske?

**Comment by llaske** [comment]
Sure it will be a nice feature. Thought I will not call it "batch actions" because batch actions are already supporting using Export/Import features.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/249
Also do multiple action in Users view.
