### ISSUE TITLE
"request" library has been deprecated

### ISSUE THREAD

**Issue by NikhilM98** [llaske/sugarizer-server#254]
The _[request](https://github.com/request/request)_ library has been deprecated. According to [Issue #3142](https://github.com/request/request/issues/3142) in its official repository, _request_ will stop accepting new features and it will stop considering breaking changes.
https://github.com/llaske/sugarizer-server/blob/6319475cb73cc2135d9cf3bcc08e677fd422e8b8/package.json#L27

This library is used in Sugarizer Server dashboard controllers to make HTTP requests.

We might need to replace _request_ with [alternatives](https://github.com/request/request/issues/3143).

I think [superagent](https://www.npmjs.com/package/superagent) would be a good alternative as it supports callbacks.

**Comment by NikhilM98** [comment]
@llaske @tarunsinghal92 what do you think?

**Comment by tarunsinghal92** [comment]
Sounds good to me 👍

**Comment by llaske** [comment]
Oooch, bad news. 
Why not superagent but we have to evaluate first what it cost to change the code: lot of files are impacted.
@NikhilM98 could you try to migrate on a small part (just in one isolated file) to test and measure the impact of the change?

**Comment by NikhilM98** [comment]
@llaske sure. I'll do it.

**Comment by NikhilM98** [comment]
Fixed in #260
