### ISSUE TITLE
Handling sessions across multiple instances, kubernetes compatibility

### ISSUE THREAD

**Issue by ksraj123** [llaske/sugarizer-server#262]
When there are more than one instance of sugarizer-server in a kuberentes deployment then the user may get redirected to login page when he either tries to log in or access any route after login.
![Peek 2020-04-14 20-13](https://user-images.githubusercontent.com/39027928/79238751-677daf00-7e8d-11ea-9c38-0360ec1e9454.gif)

A sugarizer deployment on Google Kubernetes Engine with 3 instances of sugarizer-server can be accessed here to explore the issue - http://34.84.103.197:8080/dashboard/login  
A sample helm chart is developed which is being user for deployment, it can be accessed [here](https://github.com/ksraj123/sugarizer-server-k8s-ansible/tree/master/sugarizer-chart)
A default admin account has been added for testing purpose, 
username - defaultuser
password - password

Currently no session store is used so it defaults to `MemoryStore' . In kubernetes environment there are multiple instance of sugarizer-server and the request can be routed to any one these, I guess this is the root cause of the issue as one instance will not be aware of a session in another instance's memory. 

Also it is [not recommend](https://github.com/expressjs/session#sessionoptions) to use default `MemoryStore` as it is prone to memory leaks.

**Comment by llaske** [comment]
A Helm chart has been created to manage deployment of Sugarizer Server on Kubernetes.
See [here](https://github.com/NikhilM98/sugarizer-chart) for more.
