### ISSUE TITLE
Trouble getting sugarizer server to connect to MongoDB from Glitch

### ISSUE THREAD

**Issue by joshuaalm** [llaske/sugarizer-server#268]
I have forked the sugarizer-server repository and created a Glitch project, https://joshuaalm-sugarizer-server.glitch.me, and I'm struggling to get that project to connect to my own private MongoDB cluster, despite using the correct username, password, hostname and allowing that project domain's IP in the cluster's firewall rules.

**Comment by llaske** [comment]
Are you able to access your server from the outside?
An easy way to test is to open the URL `http://<serveraddress>[:port]/api` from your browser?

You should receive a JSON with the properties of your server.
For example:

     https://try.sugarizer.org/api

Give:

       {"name":"Sugarizer Server","description":"Server for testing only: do not use for production, subject to reboot/erase","web":"443","presence":"8039","secure":true,"version":"1.2.0","options":{"min-password-size":"4","statistics":true,"cookie-age":"172800000"}}

**Comment by joshuaalm** [comment]
I just tried that, and I still don't get a response.  The logs show "Waiting for DB... (MongoServerSelectionError)"

**Comment by joshuaalm** [comment]
The full address to the API route for my glitch is https://joshuaalm-sugarizer-server.glitch.me/api

**Comment by llaske** [comment]
> I just tried that, and I still don't get a response. The logs show "Waiting for DB... (MongoServerSelectionError)"

So it means that your Sugarizer Server is not able to connect to MongoDB. 

I'm not a MongoDB expert but regarding the documentation on `MongoServerSelectionError`, it look like there is an issue with connection to your MongoDB cluster. 
Is there anything special to mention to the connection string to connect to a MongoDB cluster? 
[Here](https://github.com/llaske/sugarizer-server/blob/dev/config/wait4db.js#L41) is the Sugarizer Server source code to connect to MongoDB.

**Comment by llaske** [comment]
Closed due to lack of activity.
