### ISSUE TITLE
Warning: Accessing non-existent property with node.js

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-server#272]
There is some warnings when launching Sugarizer Server on node.js 14+ like `Warning: Accessing non-existent property 'XXX' of module exports inside circular dependency`.
See:

```
(node:10451) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10451) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:10451) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:10451) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
   _____                        _              
  / ____|                      (_)             
 | (___  _   _  __ _  __ _ _ __ _ _______ _ __ 
  \___ \| | | |/ _` |/ _` | '__| |_  / _ \ '__|
  ____) | |_| | (_| | (_| | |  | |/ /  __/ |   
 |_____/ \__,_|\__, |\__,_|_|  |_/___\___|_|   
                __/ |                          
               |___/                           
Server for Sugarizer application v1.3.0
node v14.15.0
Settings file './env/sugarizer.ini'
Presence is listening on port 8039...
API is listening on port 8080...


```

It doesn't seems to prevent Sugarizer Server to work right.

**Comment by llaske** [comment]
Fixed by https://github.com/llaske/sugarizer-server/commit/45d9cd6c2b68707b7627f8e346d4d0618ad65615

**Comment by holta** [comment]
@llaske could you consider a possible release 1.3.1 (of Sugarizer Server) that includes this fix — so that Internet-in-a-Box can include this fix for Node.js 14 ?

**Comment by llaske** [comment]
> @llaske could you consider a possible release 1.3.1 (of Sugarizer Server) that includes this fix — so that Internet-in-a-Box can include this fix for Node.js 14 ?

Hmmm. It's not planned. 
It's really a cosmetic issue. Everything works fine.
