### ISSUE TITLE
Sever not accessible after docker compose on widows.

### ISSUE THREAD

**Issue by ricknjacky** [llaske/sugarizer-server#278]
Followed the steps on running the sugarizer server locally as described in `readme.md` file, got the following error:- 

Setup :- 
![Screenshot (643)](https://user-images.githubusercontent.com/50985033/113050741-cd5c6700-91c2-11eb-891d-14fcf8cd5c80.png)

Nothing opens up/shows up after docker build:-
![image](https://user-images.githubusercontent.com/50985033/113050815-e49b5480-91c2-11eb-8841-cc05a150029b.png)

The image has been successfully been built and status is `running` as well on docker windows application:-

![image](https://user-images.githubusercontent.com/50985033/113051013-24623c00-91c3-11eb-8338-173f586e63ef.png)

Looking forward to suggestions on obviating this error.

**Comment by llaske** [comment]
Hmmm. Something should goes wrong.
Could you launch `docker-compose start` instead of `docker-compose up`. So you could see directly what happens.

**Comment by ricknjacky** [comment]
> Hmmm. Something should goes wrong.
> Could you launch `docker-compose start` instead of `docker-compose up`. So you could see directly what happens.

Thanks a lot! It works.
I'd like to mention something however,
![Screenshot (649)](https://user-images.githubusercontent.com/50985033/113223071-fd306b00-92a5-11eb-9577-a8b81e69c1dd.png)

`docker-compose start` works only after `docker-compose up -d` and it makes sense too, can't start a container server before creating/composing it. 

Should I, update the documentation markdown file accordingly for "Docker Desktop" users i.e. windows users?

**Comment by llaske** [comment]
Okay so seems that the error was related to the fact that you've not call the `generate-docker-compose.sh` script.
Right?

**Comment by ricknjacky** [comment]
> Okay so seems that the error was related to the fact that you've not call the `generate-docker-compose.sh` script.
> Right?

I think not, you can see in the screenshot attached above. I did follow the readme guide diligently, but the command that solved the issue was 

`docker-compose start` and it should be noted that, this command should be called after `docker-compose up -d`

**Comment by llaske** [comment]
Like mentioned in the [documentation](https://docs.docker.com/compose/reference/up/) `docker-compose up` command "Builds, (re)creates and starts" containers. So `docker-compose start` should not be need.

Don't know what happens on your side. Did you already use docker on your computer?

**Comment by ricknjacky** [comment]
> Don't know what happens on your side. Did you already use docker on your computer?

Yes I have and I presume I didn't make myself clear the first time around.

The documentation guides us to use `docker-compose up -d` and this runs the container in detach mode. So, docker-compose start is supposed to be run after it. If, we don't want that we can just update the README.md i.e. change 
`docker-compose up -d` to `docker-compose up`

Reference :- [documentation FAQ](https://docs.docker.com/compose/faq/#whats-the-difference-between-up-run-and-start)

**Comment by llaske** [comment]
On a server, `docker-compose` should really be launched with the `-d` option because the terminal could be closed after the command. So I don't see a good reason to change documentation.
