### ISSUE TITLE
Sugarizer-server port conflict

### ISSUE THREAD

**Issue by markknit** [llaske/sugarizer-server#287]
I'm trying to install sugarizer-server on a Ubuntu 18.04 system using Nginx. I used the docker image, but when I try to finalize the install it fails due to a conflict on port 8080. There is already a service running that is bound to that port that I can't move. I tried changing the sugarizer.ini file to change the port, but it does not seem to have any effect on the install process - it still fails with the same error. What is the correct process for changing the sugarizer-server/docker port assignment, and then starting the sugarizer node? 

BTW: I also tried to install sugarizer-server without docker, but ran into a different problem - the npm superagent is deprecated. Is there a way to upgrade the superagent?

Thanks, Mark K

**Comment by NikhilM98** [comment]
If you use Docker Compose to bring the stack up, then it should automatically map port 8080 to port 80 [here](https://github.com/llaske/sugarizer-server/blob/master/docker-compose.yml#L27).

Docker Compose instructions are given [here](https://github.com/llaske/sugarizer-server#running-sugarizer-server). You can change the port from port 80 to any other port in docker-compose.yaml.

**Comment by NikhilM98** [comment]
If you want to update superagent then maybe you can use open package.json file, set `"superagent": "^7.0.0",` and try `npm install` again.

I have not tested the compatibility of the newer version, but given that superagent rarely has any [breaking changes](https://www.npmjs.com/package/superagent#upgrading-from-previous-versions), so you can give it a try.

**Comment by markknit** [comment]
Thanks for the response. Changing the port in docker-compose.yml worked. However, there was another issue - the sugarizer-server folder is setup as root owned, so it wouldn't load. I changed it to www-data and it works fine now.

**Comment by llaske** [comment]
> the sugarizer-server folder is setup as root owned
We're going to adapt the documentation to add recommendation regarding use of sudo.
Let's continue [here](https://github.com/llaske/sugarizer-server/issues/289).
