### ISSUE TITLE
Make the docs clear about creating the user when running docker

### ISSUE THREAD

**Issue by usmanmuhd** [llaske/sugarizer-server#29]
The docs are not exactly clear about where to run the `sh add-admin.sh admin password http://127.0.0.1:8080/auth/signup` command when using docker. Running it on host machine gives 
```
{"error":"You don't have permission to perform this action","code":19}
```
Make it clear that it should be run inside the container.

**Comment by ashish0910** [comment]
@usmanmuhd The above command can be run when you are in the sugarizer-server directory on terminal / command line . Running it in container in not necessary . It will work even if you do not have docker installed on your system .

**Comment by usmanmuhd** [comment]
@ashish0910 it does not work on terminal as I have stated above when using docker. What I said was to make it clear to future contributors that it should be run inside the docker container.

**Comment by ashish0910** [comment]
@usmanmuhd what error did you get when running it on terminal ?

**Comment by usmanmuhd** [comment]
```
╭─usman at lenovo in /home/usman/projects/sugarizer-server (classroom …11)
╰─λ sh add-admin.sh admin password http://127.0.0.1:8080/auth/signup           0 < 12:18:45
HTTP/1.1 401 Unauthorized
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE
Access-Control-Allow-Headers: x-key,x-access-token
Content-Type: application/json; charset=utf-8
Content-Length: 70
ETag: W/"46-U7KcX/ScIxrxPhVhwl1xGptBqWw"
set-cookie: connect.sid=s%3AG1hRvU1uWu45kOFWpNsFKj43y9dsPGmN.rozd3nGcAxJsh%2F9Izq3SUpfn196JNcNvIqo%2BJaAO15g; Path=/; Expires=Tue, 26 Feb 2019 07:12:51 GMT; HttpOnly
Date: Sun, 24 Feb 2019 07:12:51 GMT
Connection: keep-alive

{"error":"You don't have permission to perform this action","code":19}
```

**Comment by llaske** [comment]
For security reason, you can't signup as Dashboard admin except if you're on the Sugarizer server itself.
In Docker, it means that you need to open a terminal on the container to launch the command add-admin script.
Sure it could be add in the documentation. 
BTW I think it could be better to find another way to create the initial Dashboard admin account. Any suggestion is welcome.

**Comment by usmanmuhd** [comment]
I think the better way would be to have a sign up page for one time. The admin could sign up through the browser itself for the first time after deployment.

**Comment by llaske** [comment]
@usmanmuhd no because if someone install a new server and don't think to create immediately the admin account, anyone could create it before him.

**Comment by usmanmuhd** [comment]
Yeah that's there. But I have seen some other softwares use the same strategy and enforce that the admin creates an account first.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/commit/2ae8ef4368e27771b129e4fb40dfb882f8fbb7e6
