### ISSUE TITLE
Improving the UX of desktop toolbar 

### ISSUE THREAD

**Issue by ishubham21** [llaske/sugarizer-server#290]
![Screenshot from 2022-02-19 13-33-17](https://user-images.githubusercontent.com/34435822/154792611-b380b697-8e43-4db0-ab30-a0e7510e1dde.png)

1. There are two different buttons to toggle between list-view and radial-view. Wouldn't it be nice to have a single button (say `toggle list view`) that would do the task? We can update the icon with each toggle too. 
2. Currently the search bar is oddly placed, it can be moved more towards the left so that it looks evenly placed. In fact, how about we use flex-box to position all the times in the toolbar, which would eliminate the effort of styling using `position: absolute` for each screen?

**Comment by NikhilM98** [comment]
This issue is not directly related to Sugarizer Server. Can you move this issue to [sugarizer/issues](https://github.com/llaske/sugarizer/issues)?
