### ISSUE TITLE
Adding GitHub Workflows/Actions/CI

### ISSUE THREAD

**Issue by ishubham21** [llaske/sugarizer-server#293]
Currently, the repository lacks GitHub Actions/workflows or GitHub CI. Some of the proposed additions are -
 
1. Merge conflict watcher that label PRs as `merge-conflict` if there's a merge conflict in it - can be done for both master and dev branches. 
2. Welcome first-time contributors (on new PR/issues) with a message. 
3. A [codeQL](https://codeql.github.com/docs/codeql-overview/about-codeql/) to check vulnerabilities across the repository. This can be configured for 2 cases - when a new PR is created, a CRON job that runs every Monday at 00:00 UTC, maybe? 
4. A workflow to close issues/PR that have not seen any activity in the last 45 days with prior 7-day notice. 
5. Issue templates for - bug reports, documentation updates, and feature request
6. Pull Request template.
7. Automated testing that installs the dependencies and runs `npm test` whenever a PR is made. 
7. Anything else that is important and I missed out. 

I'd love to hear suggestions/additions on this. 
CC @NikhilM98 @llaske

**Comment by llaske** [comment]
Thanks for these suggestions.
I think the most interesting idea is the 7th. 
BTW I'm not familiar with GitHub Actions/CI. I don't know what we need to do that.
@NikhilM98 what do you think?

**Comment by NikhilM98** [comment]
> BTW I'm not familiar with GitHub Actions/CI. I don't know what we need to do that.

It's possible to research and set-up GitHub Actions and CI in the forks of the repository. After that PR with configuration can be created and manual configuration steps could be shared with @llaske so that Lionel can configure Sugarizer repositories.

**Comment by NikhilM98** [comment]
> Anything else that is important and I missed out.

I guess we can add git hooks to lint and test the code too.

**Comment by dhwaj1902** [comment]
> I guess we can add git pre-commit hooks to lint and test the code.

@NikhilM98 can you please check I have made a PR regarding git pre-commit to run tests.

**Comment by llaske** [comment]
I suggest to just add a Github action to run unit testing each time a commit is done on dev branch.

**Comment by NeerajGartia21** [comment]
Can I work on on this issue or is any one actively working on this?

**Comment by NikhilM98** [comment]
@NeerajGartia21 PR #381 has made some promising progress with this issue. It has some minor issues such as unnecessary file changes and large number of commits which need to be resolved, but the feature seems to be working fine.

Feel free to test the application and create new issues if you find any bugs in the application.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/384

**Comment by AviGawande** [comment]
@NikhilM98 does this issue is open to work. so that i can contribute to it 
if yes then do suggest me.

**Comment by llaske** [comment]
@AviGawande no, the issue is close.

**Comment by AviGawande** [comment]
@llaske could you please tell me from where i will get to know about 2024 gsoc program.
please do reply..

**Comment by llaske** [comment]
@AviGawande SugarLabs is not yet part of GSoC 2024.
