### ISSUE TITLE
padding from left required in language selection menu list

### ISSUE THREAD

**Issue by codebloded** [llaske/sugarizer-server#294]
Screenshot below :arrow_down: 
Can i fix this selection menu? @llaske  
#### i wrote the code and fix this thing .! it is good to make a pull request?

![e4603fb2-d4d0-48b6-a833-684de82d1237](https://user-images.githubusercontent.com/48005711/155880936-6b194c0c-0fda-4367-87d0-26d0d4d82abe.jpeg)
?

**Comment by llaske** [comment]
Yes sure. It could be improved. Don't forget to test with different window size.

**Comment by llaske** [comment]
Closed due to lack of activity.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/commit/7e1cec20a4ece69230cd703bd8e1811bfa33598c
