### ISSUE TITLE
Unable to start the docker container server

### ISSUE THREAD

**Issue by dhwaj1902** [llaske/sugarizer-server#297]
when I execute the command ``docker-compose up -d`` it is showing this error in windows 11
![image](https://user-images.githubusercontent.com/57860123/157654623-da504659-b4cf-4fb6-88b9-c73f65e6cb1b.png)
while the mongo container is running fine.

**Comment by khareyash05** [comment]
install node_modules first in the server

**Comment by NikhilM98** [comment]
There's no need to install node locally.
Follow the steps here to fix the issue: https://github.com/llaske/sugarizer-server/blob/099b6d4da5b9a3241f96a951849dd06114cfd670/docs/install.md

**Comment by NikhilM98** [comment]
Basically you need to run `sh generate-docker-compose.sh` first
