### ISSUE TITLE
Adjust the text to center of the panel

### ISSUE THREAD

**Issue by khareyash05** [llaske/sugarizer-server#298]
I would like to adjust the language text to the center of the panel
![Screenshot from 2022-03-11 19-53-30](https://user-images.githubusercontent.com/60147732/157886006-1135ab4a-5137-4179-9c56-cef38b01f635.png)

**Comment by llaske** [comment]
Duplicate https://github.com/llaske/sugarizer-server/issues/294

**Comment by codebloded** [comment]
> Duplicate #294
@llaske  done is  #314
