### ISSUE TITLE
 validation in client side for  inputs before  sending request

### ISSUE THREAD

**Issue by mohantechnology** [llaske/sugarizer-server#302]
If  /dashboard/login page 
![Screenshot_6](https://user-images.githubusercontent.com/71864565/158078804-a2d923ba-2f5b-49b8-a45f-06f0d343037f.png)
 suppose if  we click login button without filling anything in input field then also the form submitted , 
To prevent this we can add some  client side validation using javascript so that form only submit after some basic validaton

**Comment by NikhilM98** [comment]
Sugarizer-Server forms does not depend on client side validation. If you propose to implement client side validation in Sugarizer-Server, then it needs to be implemented in all the forms in the UI.

At this moment, the simplest thing which can be implemented here is HTML input "required" attribute. But it will interfere with the "Password cannot be blank" popup on submitting the form.

@llaske what's your opinion on this?

**Comment by Shreyas-SAS** [comment]
> suppose if we click login button without filling anything in input field then also the form submitted , To prevent this we can add some client side validation using javascript so that form only submit after some basic validaton

I support the change. It seems that if the form gets submitted even when blank then it may be seen as a vulnerability to DDOS attack. It will be pretty easy to create automation to click on a button. this may lead to overflow of request on the server that may push it to its limits. 

A validation may at the least increase the complexity of the script making it a bit difficult if not completely stop it.

**Comment by mohantechnology** [comment]
Added a  simple validation before sumitting form
if will prevent submition in  following cases : 
  - if  username is empty 
  - if  password is empty 
  - if  only white space is filled in input field
  
Used similar  notification  popup that is used for  displaying other messages
 
[changes here](https://github.com/llaske/sugarizer-server/pull/305/commits/36adf43623c60c877bb9cf702dc5ae3cba634ab3)

if is beneficial then we can add simililar thing for all other forms

**Comment by mohantechnology** [comment]
since sugarizer-server also works for different languages  and  so it is not a good idea to add client side validation notifications
