### ISSUE TITLE
Feature to import/insert user through  uploading  csv file 

### ISSUE THREAD

**Issue by mohantechnology** [llaske/sugarizer-server#306]
currently adding bulk users is supported only from command line . we can add feature to  insert/import users through  front-end  by uploading csv file. And extending this feature to support  excel file also

**Comment by llaske** [comment]
It's already possible from the Dashboard (see "Import users" button).

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/981841/158605141-ce474a87-e052-49ad-b49e-9959e9b833ec.png">

**Comment by llaske** [comment]
It's not a request coming from the field. They requested explicitly CSV files.
People are more familiar with CSV. Plus, handling Excel files with multiple format (header, template, styles, ...) could make things difficult.

**Comment by mohantechnology** [comment]
Okay ,Thanks a lot for your support
