### ISSUE TITLE
Getting internal server error when trying to make a admin account

### ISSUE THREAD

**Issue by saga2405** [llaske/sugarizer-server#310]
`sh add-admin.sh admin password http://127.0.0.1:80/auth/signup`

I'm using this command in docker container CLI and it throws back internal server error

**HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE
Access-Control-Allow-Headers: x-key,x-access-token
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 1145
set-cookie: connect.sid=s%3AekPmznPSJSB7vLeu6KKsNbCBeU6bEyuJ.r%2FVDIuOr9H%2Bu95PD4YFpGMp8DvuM9yJ1UE%2FQ0p5mF2c; Path=/; Expires=Mon, 21 Mar 2022 06:45:08 GMT; HttpOnly
Date: Sat, 19 Mar 2022 06:45:08 GMT
Connection: keep-alive

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
 in JSON at position 14<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at exports.checkAdminOrLocal (/sugarizer-server/api/controller/auth.js:354:19)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/sugarizer-server/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/sugarizer-server/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/sugarizer-server/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/sugarizer-server/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /sugarizer-server/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (/sugarizer-server/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/sugarizer-server/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at serveStatic (/sugarizer-server/node_modules/serve-static/index.js:75:16)</pre>
</body>
</html>**

**Comment by saga2405** [comment]
can anyone please help to resolve this

**Comment by llaske** [comment]
Could you explain the context? Are you using Docker or are you using directly node.js?

**Comment by saga2405** [comment]
I'm using docker for this. As running this command directly on nodejs is giving permission issues

**Comment by llaske** [comment]
You should launch this command from inside the Docker container. It means attaching a bash shell on the running docker instance to launch the command. If you're not familiar with docker, you could attach a bash to an instance by running:

`docker exec -it <IdOfDockerForSugarizerServer> /bin/bash`
