### ISSUE TITLE
sort users in admin dashboard

### ISSUE THREAD

**Issue by saga0p** [llaske/sugarizer-server#315]
currently, the user list in `http://127.0.0.1:8080/dashboard/users/` is not sorted 
we can sort the users based on `last seen` or `account created time`

**Comment by saga2405** [comment]
I've checked again, so there's already sorting available based on last seen but it's not clearly visible. so when we click on last seen button it sorts the data but we can add a separate sort by button/dropdown : with options including 1. sort by last seen
2. sort by created at

>

**Comment by saga2405** [comment]
@llaske can i get your inputs on this

**Comment by llaske** [comment]
It seems logical to click on the header to sort. Not sure to understand your idea of button/dropdown.

**Comment by llaske** [comment]
Closed due to lack of activity.
