### ISSUE TITLE
 Some  of  the Text Content  is not translated

### ISSUE THREAD

**Issue by mohantechnology** [llaske/sugarizer-server#320]
In below screen shots  text are not   replaced  when selected Spanish  language
![Screenshot_1](https://user-images.githubusercontent.com/71864565/160480535-d68e2b9b-cd46-4a7a-bd49-3a59a93e0bcf.png)
![Screenshot_2](https://user-images.githubusercontent.com/71864565/160480543-d534b83c-88ce-47d6-861c-7594df6e11b0.png)

and also only button text is translated for hindi language  
![Screenshot (4390)](https://user-images.githubusercontent.com/71864565/161444379-b255dbe1-9334-4468-b192-6ffc25d4fac2.png)

**Comment by mohantechnology** [comment]
the text "if you lose success to ... " 
is not translated to hindi when we select hindi language 
so i want to ask if is it  made to look like that?

**Comment by llaske** [comment]
It's not an issue in the source code. It's related to localization: https://translate.sugarizer.org/projects/sugarizer/sugarizer-server/
