### ISSUE TITLE
sort activities in admin dashboard based on name (alphabetically)

### ISSUE THREAD

**Issue by saga0p** [llaske/sugarizer-server#321]
currently, there's no sorting in activities section in dashboard/activities. we can sort all the activities based on the name

**Comment by NikhilM98** [comment]
It's possible and would be convenient. However, the implementation needs to be compatible with activity reorder by drag and drop feature. Currently the order of the activities is relevant to Sugarizer, so the idea of sorting the activities may not be compatible with the existing feature.

Can you describe in detail what your visualization of sorting by name while preserving existing feature looks like?

**Comment by llaske** [comment]
Closed due to lack of activity.
