### ISSUE TITLE
Sugarizer-Server LogOut Bug

### ISSUE THREAD

**Issue by MananJain2002** [llaske/sugarizer-server#328]
https://user-images.githubusercontent.com/63538502/163693625-64a86105-0caa-4617-bd9f-b9414d0c39ec.mp4

After logging off and doing undo it should redirected towards login page

**Comment by llaske** [comment]
It's not bug.
Clicking back button could always cause errors.

**Comment by MananJain2002** [comment]
Hi @llaske sir I'm not sure why it's not a bug even if it's a children's app its better for a website to be more securer anyway I managed to fix this issue here https://github.com/llaske/sugarizer-server/pull/329 please do review it. I have even attached a video for demonstration.

**Comment by llaske** [comment]
Not reproducible on recent Sugarizer Server version.
