### ISSUE TITLE
Consistency in language of users

### ISSUE THREAD

**Issue by ashish0910** [llaske/sugarizer-server#33]
When we create a new user through http://127.0.0.1:8080/dashboard/users/add we have to have to enter language of the user but however the admin can enter any value without any validation . The idea is to add a select option which allows admin to add only specific values which will be consistent throughout the database . (like English , Hindi .. etc )
![screenshot 2019-02-24 at 11 47 04 pm](https://user-images.githubusercontent.com/30404493/53303281-85094700-388e-11e9-99c2-e521dcc626f7.png)

**Comment by llaske** [comment]
@ashish0910, you're right a value without any control is not ideal.
May be we could propose a set of value. 
For students the value depend of the Sugarizer client language set, currently [here](https://github.com/llaske/sugarizer/blob/dev/js/dialog.js#L583) is the value list.
For admins the value depend of the Sugarizer admin language set, currently [here](https://github.com/llaske/sugarizer-server/blob/dev/dashboard/views/login.ejs#L7) is the value list.

**Comment by ashish0910** [comment]
I will start working on it .

**Comment by llaske** [comment]
Merge in https://github.com/llaske/sugarizer-server/commit/3a2e50d4b03dd7ba896a17652dab4ca45f3d2c12
