### ISSUE TITLE
Link to existing MongoDB

### ISSUE THREAD

**Issue by JamesM92** [llaske/sugarizer-server#337]
I have an already running mongoDB server, I can't find any means to link to an already running mongoDB server while starting up the sugarizer docker compose file.

Is there something I'm missing, or is this just not an option?

**Comment by llaske** [comment]
Of course it's possible to run Sugarizer Server with an existing MongoDB server.
In that case you just need a single container, you could use [this file](https://github.com/llaske/sugarizer-server/blob/dev/docker/Dockerfile-standalone) as a model. 
Read [architecture documentation](https://github.com/llaske/sugarizer-server/blob/dev/docs/architecture.md) for reference.

**Comment by llaske** [comment]
Closed due to lack of activity.
