### ISSUE TITLE
Sugarizer Dashboard Navbar language selector has a css issue

### ISSUE THREAD

**Issue by shubhangNarain** [llaske/sugarizer-server#343]
Hey @llaske , I found a css issue in the navbar of sugarizer dashboard. Attaching an image to show the issue. This might be because of the `.form-control, .form-group .form-control` selector. We can simply align the text to rectify it.
![Inkeddash_2_langCSSupdated](https://user-images.githubusercontent.com/80174035/213519245-12878798-7227-46b3-9069-e85fa2ec9cfc.jpg)

**Comment by shubhangNarain** [comment]
@llaske Please review and merge #344

**Comment by llaske** [comment]
It doesn't appear on my side.

![image](https://user-images.githubusercontent.com/981841/213554440-5e892a57-b7d1-4c79-b729-3231a6d3fd3a.png)

Did you try on the latest dev branch?

**Comment by shubhangNarain** [comment]
My mistake, didn't pull the changes from the `dev` branch. My bad.
