### ISSUE TITLE
Need of an update in sugarizer-server/docs/install.md for macOS

### ISSUE THREAD

**Issue by mayank190801** [llaske/sugarizer-server#346]
-- Detailed Issue -- 

 - There have been quite a few changes in the way that NodeJS and MongoDB is now installed in local system.
 - Since the release of MacOS Catalina the /data/db is made strictly read-only and hence we can not create or delete folders in that space. 
 - There are a couple of new steps required for setting up mongoDB and the default location for the data is now /opt/local/var/mongodb.
 

<img width="1285" alt="Screenshot 2023-02-08 at 10 47 10 AM" src="https://user-images.githubusercontent.com/54149585/217441113-fd7d27b4-97ca-423e-873c-4e9d0baff47a.png">

**Comment by llaske** [comment]
You're right.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/347
