### ISSUE TITLE
Fix required in sidebar to achieve consistency

### ISSUE THREAD

**Issue by mayank190801** [llaske/sugarizer-server#348]
As you can see in the video - 
 - Between window-width from 768px to 921px the logout and profile button doesn't appear, which creates inconsistency in the overall sidebar. 

A need for creating consistency till the max-width of 922px could be achieved in the sidebar.
In which there could be no dropdown option, but only logout and profile button appears as soon as the navbar collapses.

https://user-images.githubusercontent.com/54149585/217568863-9d886a68-24cc-4c1e-9a22-74ce62d93541.mov

**Comment by mayank190801** [comment]
@llaske I would like to know if you think this issue needs some fix?

**Comment by llaske** [comment]
You're right, it could be improved.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/353
