### ISSUE TITLE
Activities list not completely centered

### ISSUE THREAD

**Issue by mayank190801** [llaske/sugarizer-server#351]
-- Detailed Issue -- 

- There have been some few pixels space left inside each div, inside of list element of Activites.
- Due to which the text, icon, number is not completely centered with respect to the list .
- There is a more space in the bottom and less from the top.

![Space_Beneath](https://user-images.githubusercontent.com/54149585/218071054-2aef1f32-92ed-4df9-863d-079c0806c49a.png)

**Comment by llaske** [comment]
Really not a visible issue. I don't think any user have detected that.

**Comment by mayank190801** [comment]
Should I close this issue then?

**Comment by llaske** [comment]
> Should I close this issue then?

Yes
