### ISSUE TITLE
Auto reload when I change the option from dropdown

### ISSUE THREAD

**Issue by usmanmuhd** [llaske/sugarizer-server#36]
I have to press "show results" button now to see results after changing option from dropdown. It can be changed to autoreload to make UX better.
![ezgif-1-13aa0167392a](https://user-images.githubusercontent.com/26684281/53410167-05dc5600-39e9-11e9-8326-af80aed377d6.gif)

**Comment by llaske** [comment]
If there is lot of records in the database because it will multiply request on the server.  Because server could be host on a RaspberryPI, I don't think it's pertinent.

**Comment by usmanmuhd** [comment]
I think pagination would solve that issue. We could just pull 10 at a time.

**Comment by llaske** [comment]
Pagination is already implemented.

**Comment by usmanmuhd** [comment]
So you still think that auto reload is not advisable?

**Comment by llaske** [comment]
Yes
