### ISSUE TITLE
Update the Popover box 

### ISSUE THREAD

**Issue by mayank190801** [llaske/sugarizer-server#360]
Need For Enhancement 

- I have found that Sugarizer and Sugarizer-Server used to have similar types of Popover boxes before. Recently inside the dev-branch of Sugarizer, the popover box is updated and has a much better look and feel to it.

- I would like to work on this enhancement by updating the Sugarizer-Server popover box as well.

-- Updated Popover Box inside Sugarizer (dev branch) -- 
<img width="281" alt="Screenshot 2023-02-16 at 10 39 21 AM" src="https://user-images.githubusercontent.com/54149585/219280080-9161c2ba-c6a3-4010-b13b-4e219a19149b.png">

-- Current Popover Box inside Sugarizer-Server (dev branch) -- 
<img width="327" alt="Screenshot 2023-02-16 at 10 32 13 AM" src="https://user-images.githubusercontent.com/54149585/219280058-33c7766f-c10c-4d18-9a2b-d2617f1dceaf.png">

**Comment by mayank190801** [comment]
@llaske What are views regarding it? 
I have also made a pull request regarding this enhancement.

**Comment by mayank190801** [comment]
@llaske Is there a community group (slack, discord etc.) for people contributing to Sugarizer or Sugarizer-Server?

**Comment by llaske** [comment]
It's not related to the popover box, it comes from the library used for tutorial.
See [here](https://github.com/llaske/sugarizer/issues/1090) for more.
It will be a task for the GSoC to migrate.

**Comment by mayank190801** [comment]
Okay. So can I try to resolve it or should I leave it for GSoC?

**Comment by llaske** [comment]
Yes you can start working on it. I've opened a dedicated issue here https://github.com/llaske/sugarizer-server/issues/363.
You can close the current issue.

**Comment by mayank190801** [comment]
Okay. Thank you.
