### ISSUE TITLE
npm start failed , server crashed

### ISSUE THREAD

**Issue by parteekcoder** [llaske/sugarizer-server#368]
Reproduce

1. run npm install
2. run command :- npm start
@llaske 
Server will crash as it is not able to find the correct path at here in these two files  
https://github.com/llaske/sugarizer-server/blob/master/api/controller/activities.js#L28

https://github.com/llaske/sugarizer-server/blob/master/api/controller/journal.js#L108

**Comment by codebloded** [comment]
@parteekcoder can give some screenshots of your terminal ?

**Comment by parteekcoder** [comment]
> @parteekcoder can give some screenshots of your terminal ?

Sure @codebloded , could you please guide me how can I get into sugarlabs gsoc project this year

**Comment by parteekcoder** [comment]
@codebloded also when I ran `npm run test` it failed , as it also not able to find the files

Could you please help me?

**Comment by codebloded** [comment]
which node/npm version you use?

**Comment by parteekcoder** [comment]
> which node/npm version you use?

node version 16.18.2 

But this is not node error i guess it not able to find the path

**Comment by parteekcoder** [comment]
> Reproduce
> 
> 1. run npm install
> 2. run command :- npm start
>    @llaske
>    Server will crash as it is not able to find the correct path at here in these two files
>    https://github.com/llaske/sugarizer-server/blob/master/api/controller/activities.js#L28
> 
> https://github.com/llaske/sugarizer-server/blob/master/api/controller/journal.js#L108

@codebloded check these lines path is wrong

**Comment by parteekcoder** [comment]
hey @llaske please see this line https://github.com/llaske/sugarizer-server/blob/master/env/sugarizer.ini#L25

the path is wrong that's why getting the above mentioned error

Also @codebloded please help in this if I am wrong?

**Comment by llaske** [comment]
@parteekcoder you're supposed to change the path in `sugarizer.ini` to match your environment.
Where's located your Sugarizer directory?

**Comment by parteekcoder** [comment]
yeah But it is relative path which doesnot matter where the repo is cloned in my system

it should be `../sugarizer-server/dashboard/controllerccc

**Comment by NikhilM98** [comment]
@parteekcoder did you clone Sugarizer along with Sugarizer Server?

By default, Sugarizer Server assumers the directory structure to be like this:
- [SOME_PATH]
    - sugarizer
        - ...
        - ...
    - sugarizer-server
        - ...
        - ...
 
The client application for Sugarizer Server is Sugarizer. If you have cloned both repositories in the same folder, this environment variable does not needs to be changed.
```
[client]
path = ../sugarizer/
```

**Comment by parteekcoder** [comment]
closing as solved
