### ISSUE TITLE
Adding issue and pr templates

### ISSUE THREAD

**Issue by creyente1897** [llaske/sugarizer-server#37]
#### I am submitting a -
* [x] **Feature Request**
* [] **Bug Report**

#### Describe your bug/feature -
Currently there is no template for issue and pull request and so there are problems in a well formatted issue which can be easy to understand. So there must be a template for both.

#### Are you working on this issue? (Yes/No)
Yes

**Comment by llaske** [comment]
I don't see the interest for this today.

**Comment by creyente1897** [comment]
@llaske Ok sir
