### ISSUE TITLE
Error while requesting

### ISSUE THREAD

**Issue by parteekcoder** [llaske/sugarizer-server#371]
Reproduce

1. Start the server
2. Make a request

The function where JSON.parse() is used having req object in the parse function, It will give following error

![image](https://user-images.githubusercontent.com/100110395/220733917-ac99d16b-978c-4aef-bc4b-8127c43d9509.png)

As this is useless , we don't need to use it here 
Because we are using `bodyParser` to convert req body

**Comment by codebloded** [comment]
@parteekcoder 
Kindly check your JSON data you passed in body from Postman. It accepts whole data as a string !
console it and check what you have passed in body !

**Comment by parteekcoder** [comment]
> @parteekcoder Kindly check your JSON data you passed in body from Postman. It accepts whole data as a string ! console it and check what you have passed in body !

@codebloded yeah I have checked that But still is it failing

**Comment by codebloded** [comment]
Give me a screenshot of body that you have passed in the request from postmam

**Comment by parteekcoder** [comment]
![image](https://user-images.githubusercontent.com/100110395/220903676-51da2e88-d9f0-46d1-9854-5630a25c8194.png)

I passed json as well as stringified data

**Comment by codebloded** [comment]
> ![image](https://user-images.githubusercontent.com/100110395/220903676-51da2e88-d9f0-46d1-9854-5630a25c8194.png)
> 
> I passed json as well as stringified data

This is good but I'm expecting the screenshot of body that you have passed from the postman!
Are you using postman?

**Comment by parteekcoder** [comment]
> > ![image](https://user-images.githubusercontent.com/100110395/220903676-51da2e88-d9f0-46d1-9854-5630a25c8194.png)
> > I passed json as well as stringified data
> 
> This is good but I'm expecting the screenshot of body that you have passed from the postman! Are you using postman?

![image](https://user-images.githubusercontent.com/100110395/220906671-8694f9e3-9166-4418-811a-92fcbefcb800.png)

**Comment by parteekcoder** [comment]
> Reproduce
> 
> 1. Start the server
> 2. Make a request
> 
> The function where JSON.parse() is used having req object in the parse function, It will give following error
> 
> ![image](https://user-images.githubusercontent.com/100110395/220733917-ac99d16b-978c-4aef-bc4b-8127c43d9509.png)
> 
> As this is useless , we don't need to use it here Because we are using `bodyParser` to convert req body

hey @llaske please see this error it is due to the JSON.parse() we are using

**Comment by parteekcoder** [comment]
@llaske as we have used parsers here at https://github.com/llaske/sugarizer-server/blob/master/config/main.js#L33

There is no need to convert incoming data to JSON format here https://github.com/llaske/sugarizer-server/blob/master/api/controller/users.js#L432
  
So this line https://github.com/llaske/sugarizer-server/blob/master/api/controller/users.js#L432  produces error which I mentioned above

Refer here https://stackoverflow.com/questions/38380462/syntaxerror-unexpected-token-o-in-json-at-position-1

**Comment by parteekcoder** [comment]
@llaske as we have used parsers here at https://github.com/llaske/sugarizer-server/blob/master/config/main.js#L33

There is no need to convert incoming data to JSON format here https://github.com/llaske/sugarizer-server/blob/master/api/controller/users.js#L432

So this line https://github.com/llaske/sugarizer-server/blob/master/api/controller/users.js#L432 produces error which I mentioned above

Refer here https://stackoverflow.com/questions/38380462/syntaxerror-unexpected-token-o-in-json-at-position-1

**Comment by NikhilM98** [comment]
Yes, `req.query` is automatically parsed and it's already being treated as a javascript object by `addQuery` function.

However your postman request will still result in an error. `JSON.parse(JSON.stringify(X))` should return the original object. If it is not returning the original object, then it means `X` is not a JavaScript object.

Maybe you should consider stringifying your requests before sending them to the API endpoint.

**Comment by parteekcoder** [comment]
@NikhilM98 is there any docs for sugarizer-server

**Comment by NikhilM98** [comment]
- API Docs: Refer to [README.md](https://github.com/llaske/sugarizer-server/blob/master/README.md) for instructions on that.
- Other docs: [sugarizer-server/docs](https://github.com/llaske/sugarizer-server/tree/master/docs)
