### ISSUE TITLE
Error while logging

### ISSUE THREAD

**Issue by parteekcoder** [llaske/sugarizer-server#373]
I have stored my credentials in database
But when I am trying to logging it is not logging and redirecting me to same page

@llaske

**Comment by parteekcoder** [comment]
@llaske the superagent we are using is not able to find the url

![image](https://user-images.githubusercontent.com/100110395/220824191-fbd648e9-0ad3-4b3a-8e9d-3f3bf06d12f6.png)

**Comment by codebloded** [comment]
I'm telling you the right way to do this
- First login with sugarizer app in login 
- then check your mongodb users collection, you will find the user with `role:'student'`
- edit the `role:'student` to `admin`or `teacher`,
- then start login with same credentials you will login as a `admin` 

if your problem is different then send some recorded GIF or screenshots of UI and flow

**Comment by parteekcoder** [comment]
@codebloded 

![image](https://user-images.githubusercontent.com/100110395/220960734-0068ea30-c79c-45ff-9b34-246e0f52f7ec.png)

This is happening each time when I try to login

**Comment by parteekcoder** [comment]
> @parteekcoder I'm telling you the right way to do this
> 
> * First login from sugarizer app.
> * then check your mongodb users collection, you will find the user with `role:'student'`
> * edit the `role:'student` to `admin`or `teacher`,
> * then start login with same credentials you will login as a `admin`
> 
> if your problem is different then send some recorded GIF or screenshots of UI and flow

first I have to create the user then we can login

I have also checked in the database that this user exist

**Comment by parteekcoder** [comment]
hey @codebloded do you know why this is coming

**Comment by llaske** [comment]
@parteekcoder the `path` property in the `[client]` section should point on Sugarizer app (probably `../sugarizer`) not on `../sugarizer-server/dashboard/controller/`.

**Comment by parteekcoder** [comment]
@llaske but with this it will not work

**Comment by llaske** [comment]
@parteekcoder if you've got difficulties to run the Sugarizer Server environment directly on your system, I suggest you to use docker instead since it hide most of the complexity of the set up.

**Comment by parteekcoder** [comment]
@llaske actully this issue is due to that I am running another service at PORT=8080 , but now it is solved

So I am closing this issue now , but if you want I can mention this in the README

**Comment by llaske** [comment]
@parteekcoder good to hear.
No need to update README.
