### ISSUE TITLE
teacher not able to log in

### ISSUE THREAD

**Issue by parteekcoder** [llaske/sugarizer-server#375]
Reproduce 

1. try to login using teacher account
2. You will see this error

![Screenshot_20230301_182234](https://user-images.githubusercontent.com/100110395/222146406-f2afeae9-e44b-4ad3-8bc3-1685f4699c3e.png)
![Screenshot_20230301_182248](https://user-images.githubusercontent.com/100110395/222146411-79eeaa73-b14f-4286-bd93-774108dbd3ef.png)

**Comment by parteekcoder** [comment]
@llaske this error persist due to these lines
```
	query['_id'] = {
			$in: req.user.classrooms.map(function(id) {
				return new mongo.ObjectID(id);
			})
		};

query['_id'] = {
			$in: req.user.students.map(function(id) {
				return new mongo.ObjectID(id);
			})
		};
```

and etc.

**Comment by llaske** [comment]
Sorry it's impossible to reproduce your issue. It's probably because you're environment is incorrect or patched by your hand. We can't help you without a clear path to reproduce the issue from a standard environment.

**Comment by parteekcoder** [comment]
I just simple cloned the repo then installed the dependencies and ran the server
this my teacher object in database

![image](https://user-images.githubusercontent.com/100110395/222162911-0be21a7f-7fdb-4fa2-b273-ebb1070457ec.png)

Can you please once explain how `req.user.students` is defined as we are not passing it from the frontend

Can you please explain the steps you followed

**Comment by NikhilM98** [comment]
A teacher should be created with valid classrooms. If you create a teacher with Sugarizer Server dashboard, then it is created with classroom. Did you create this object manually?

**Comment by parteekcoder** [comment]
yes

**Comment by NikhilM98** [comment]
That explains why your object has some keys missing. It's better to create these objects from the dashboard.
