### ISSUE TITLE
Full Sceen Button Position

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [llaske/sugarizer-server#387]
Hey @llaske , I noticed the resize button in full Screen mode has a margin from left which hides some content if present and also overlaps if we have some content present.

 I recommend that we should position it to the top right corner so to have a better look and also not to hide any content if present.
Let me know what you think about it.

<img width="1440" alt="Screenshot 2023-03-08 at 9 33 57 PM" src="https://user-images.githubusercontent.com/75615092/224400814-210b71e3-50ad-4ff0-b97d-4890a049c051.png">

**Comment by llaske** [comment]
No, it's the standard position for this button.

**Comment by ABHINAV-JHA-27** [comment]
Thanks for the review. Got it.
