### ISSUE TITLE
Move Alignment in Chess Activity

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [llaske/sugarizer-server#388]
Hey @llaske , I noticed a ui issue in chess activity on server dashboard.
The moves are not aligned in a straight line.

Let me know what you think.

<img width="475" alt="Screenshot 2023-03-11 at 12 28 09 AM" src="https://user-images.githubusercontent.com/75615092/224403364-727ca6a9-8956-4420-954d-643f61403c62.png">

**Comment by llaske** [comment]
You're right, it could be better.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1329

**Comment by NikhilM98** [comment]
Great!
