### ISSUE TITLE
Blank Intro PopUp

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [llaske/sugarizer-server#389]
Hey @llaske , I noticed a bug in the constellation activity. 
If we don't give the location permission or block it then the Intro popup or help popup is blank.

<img width="1440" alt="Screenshot 2023-03-11 at 12 45 40 AM" src="https://user-images.githubusercontent.com/75615092/224406704-7b1e5b39-c6ed-4e2e-a428-0f646c7d569e.png">

**Comment by llaske** [comment]
Can't reproduce the issue. Could you detail your environment and try in different configuration?

**Comment by ABHINAV-JHA-27** [comment]
Hey @llaske , can you see that it occurs often. and sometimes gets fine after refreshing.
https://user-images.githubusercontent.com/75615092/224509109-14920374-7027-448a-b47d-bfc4194e0587.mov

**Comment by ABHINAV-JHA-27** [comment]
Hey @llaske did you have a look.

**Comment by llaske** [comment]
Sorry, seems related to your environment can't reproduce it.
