### ISSUE TITLE
show no result found message rather than Showing table headings

### ISSUE THREAD

**Issue by ashish0910** [llaske/sugarizer-server#39]
On searching for User or Classroom through search option it shows only headings of the table if no matching result is found . The idea is to show user that no User or Classroom matching your search found message rather than showing only Table headings .

![screenshot 2019-02-28 at 6 11 37 pm](https://user-images.githubusercontent.com/30404493/53567226-91d6b500-3b84-11e9-9c93-7f106438ff8b.png)

**Comment by llaske** [comment]
Seems clear that there is no result found. It's the same behavior when looking for users.

**Comment by ashish0910** [comment]
Yes , It's the same behaviour when looking for users. Showing such messages helps in better user experience .

**Comment by tarunsinghal92** [comment]
@ashish0910 Could you please make a PR with a similar screen as shown above for classroom module.

**Comment by ashish0910** [comment]
@tarunsinghal92 added in #44

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/44
