### ISSUE TITLE
Overlapping of blocks in PhysicsJS Activity

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [llaske/sugarizer-server#390]
Hey @llaske , I found a bug in the PhysicsJs activity where if we have too many blocks on the screen the blocks start to overlap.

I think its expected to touch around the circumference and not overlap

<img width="1440" alt="Screenshot 2023-03-12 at 1 33 53 AM" src="https://user-images.githubusercontent.com/75615092/224509391-9c0f7ed4-bbcf-4d06-bb74-e81637ab8048.png">

**Comment by llaske** [comment]
It's related to the physics library, not really an issue, it more a way to see what happens in a stressed environment.

**Comment by ABHINAV-JHA-27** [comment]
Got it. Thanks for letting me know.
