### ISSUE TITLE
precommit 

### ISSUE THREAD

**Issue by parteekcoder** [llaske/sugarizer-server#399]
@NikhilM98 @llaske  There can be some eslint formatting errors present in the code and can be pushed to github which is then check by the workflow 

To ease this we can add a pre commit statement which will run when contributor do commit

**Comment by ricknjacky** [comment]
@parteekcoder can you please close this issue + PR pertaining to it?

ref:- https://github.com/llaske/sugarizer-server/pull/400#issuecomment-1474900698

**Comment by parteekcoder** [comment]
Yeah sure
