### ISSUE TITLE
Getting Json parse error in API post request

### ISSUE THREAD

**Issue by NischayGoyal1** [llaske/sugarizer-server#401]
i was hitting **http://127.0.0.1:8080/auth/login/** and getting this error

![image](https://user-images.githubusercontent.com/81116984/227039986-9d4ac9cb-65e6-42de-a5ff-fe1e0ea88e30.png)

I used try and catch 
``` var user;
  try {
    user = JSON.parse(req.body.user);
  } catch (error) {
    console.error('Error parsing user JSON:', error);
    return res.status(400).json({ error: 'Invalid JSON input' });
  }```

Getting invalid json input

**Comment by raazseth** [comment]
Can you assign me this project @llaske

**Comment by llaske** [comment]
It's not an error, it's because your request don't send correctly the expected parameter
