### ISSUE TITLE
GH Issue and PR template 

### ISSUE THREAD

**Issue by samyakshah3008** [llaske/sugarizer-server#408]
## Description: 

- Currently any new user who comes up to this repository and reports a new issue ticket, we don't have a template. For a better contributor experience, also there is no template for PR while raising one. 

## Potential Solution: 

- We can create a markdown file for the same.

## Helpful links: 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

**Comment by llaske** [comment]
The amount of activity here doesn't require any additional procedures.
