### ISSUE TITLE
Install linting in the project

### ISSUE THREAD

**Issue by NikhilM98** [llaske/sugarizer-server#41]
Sugarizer server has great potential for extending its codebase. I think we should install linter (Specifically ESLint) in the project before the codebase gets too messy due to the inconsistency in the language of the users. Not having coding conventions is also a barrier to attracting contributions. Besides checking style, linters are also excellent tools for finding certain classes of bugs, such as those related to variable scope. Assignment to undeclared variables (these leak into the global scope, contaminating it and possibly causing very difficult to find bugs) and use of undefined variables are examples of errors that are detectable at lint time.

I would like to contribute to this repository by installing linter and removing the bugs related to the scope of variables and further cleaning the code. If the maintainers agree, I'm happy to work on this issue :smiley:

**Comment by tarunsinghal92** [comment]
@NikhilM98 
This is a very nice idea and I think we should have `lint` to promote coding convention. Please make sure that linting rules are flexible enough to accommodate the current design pattern.

Looking forward to reviewing the PR. 

-
TKS

**Comment by NikhilM98** [comment]
Cool!
I've already started working on the issue.
There are a lot of indentation, semicolon, and variable scope errors. I was thinking about ignoring indentation errors for now and begin from the variable scope errors.
@tarunsinghal92 can we discuss some linting rule practices on IRC?

**Comment by ahmedkrmn** [comment]
@NikhilM98 and @tarunsinghal92. There's an npm package called [prettier](https://www.npmjs.com/package/prettier) that works out of the box and can be configured as well.
It's also available as an extension for the majority of editors out there.

**Comment by Anshuman71** [comment]
@tarunsinghal92 @NikhilM98 @ahmedkrmn Prettier and eslint go hand in hand for a great codebase.
We can use 'Airbnb' style guide or can implement our own after a discussion on IRC. 
VsCode formats the code for better readability and it makes a huge diff in pull requests as of now.
So it will be great to implement a coding standard now.
Before
![Screenshot from 2019-03-17 13-31-21](https://user-images.githubusercontent.com/28081510/54487195-23e6f900-48b9-11e9-9cd1-4d8525717a83.png)
After
![Screenshot from 2019-03-17 13-31-49](https://user-images.githubusercontent.com/28081510/54487198-26495300-48b9-11e9-846f-81388af81128.png)

**Comment by NikhilM98** [comment]
@Anshuman71 thanks for the suggestion.

Actually, VS Code doesn't automatically formats the code. I think you've installed some plugin like Beautify which automatically formats the code on save.

We cannot follow the style guides like Airbnb since they'll mean huge changes in the code. We've to follow a more flexible style guide for the initial phase of linting.

Also, in my personal opinion, I think it's not a good practice to use tools that automatically format the code for you. Formatting the code is a part of learning and it should be promoted to manually format the code following the linting rules. (But it's only my personal opinion)

There's already PR #58 with the basic configuration of linting. It has been put on hold since it was not clear that we should install the linter or not.

**Comment by Anshuman71** [comment]
@NikhilM98 thanks for the follow-up. My suggestion was totally motivated by the thought of uniform coding standards.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/commit/3d6ac3c76873ff3f255520bba6d25e2024ba4cf8
