### ISSUE TITLE
Language switching not handled properly

### ISSUE THREAD

**Issue by NikhilM98** [llaske/sugarizer-server#42]
Some text on the dashboard is not being translated on switching the language using the language dropdown.

Steps to reproduce:
1. Go to Dashboard Login and login with admin credentials.
![screenshot from 2019-03-01 23-17-14](https://user-images.githubusercontent.com/24666770/53656210-954b6880-3c78-11e9-9976-d2eab3de3934.png)

2. After login. Switch language using the dropdown on the top right of the page.
![screenshot from 2019-03-01 23-17-27](https://user-images.githubusercontent.com/24666770/53656244-b4e29100-3c78-11e9-8802-d6c48b69013b.png)

3. Notice that after changing the language. The "# of Entries" and timestamp is not translated.
![screenshot from 2019-03-01 23-17-47](https://user-images.githubusercontent.com/24666770/53656382-21f62680-3c79-11e9-9ea4-dcc5501e9892.png)

4. Now change the url. Set lang=en and press enter.
![screenshot from 2019-03-01 23-17-55](https://user-images.githubusercontent.com/24666770/53656430-39351400-3c79-11e9-99e9-ebeea39419b2.png)

Boom! The text is now translated.

I would like to work on this issue. I'll submit a PR as soon as I find a fix :hammer:

**Comment by NikhilM98** [comment]
Fixed in #121

**Comment by llaske** [comment]
I'm not close issues until a new release is out.
