### ISSUE TITLE
Breaking changes due to the use of ES6 syntax

### ISSUE THREAD

**Issue by NikhilM98** [llaske/sugarizer-server#49]
@imdhruvgupta @tarunsinghal92 there are some issues which are causing breaking changes. ES6 syntax is used here which is not recognized by node until we use Babel. I think there's no need to use Babel in this project for now. This is causing breaking issues in the project. After pulling the latest code. I'm getting the error:

	> node sugarizer.js

	FATAL ERROR, uncaught exception 'Unexpected token export'
	/sugarizer-server/dashboard/controller/activities/index.js:5
	export { fakeLaunch } from "./fakeLaunch";
	^^^^^^

	SyntaxError: Unexpected token export

_Originally posted by @NikhilM98 in https://github.com/llaske/sugarizer-server/pull/34#issuecomment-468990369_

**Comment by tarunsinghal92** [comment]
@imdhruvgupta

Could you please look into this issue asap!

**Comment by imdhruvgupta** [comment]
It was working fine in docker mode. I'll check that.

**Comment by NikhilM98** [comment]
Merged #55
