### ISSUE TITLE
Sort tables in Users/Classrooms by clicking on the column header

### ISSUE THREAD

**Issue by ahmedkrmn** [llaske/sugarizer-server#78]
This is an enhancement feature that I think would be very handy if added to the project.
The admin can click on the header he/she wants to sort the table by whether it's students table, the admins table or the classrooms table.

Here are two Gifs demonstrating the functionality:
**Users (Students/Admins):**

![Users2](https://user-images.githubusercontent.com/20889958/54085449-02c95a00-4347-11e9-8d5f-82c97d4b92dd.gif)

**Classrooms:**

![Classrooms](https://user-images.githubusercontent.com/20889958/54085454-15dc2a00-4347-11e9-8399-cb6cf530b54e.gif)

**PR  #79  implements this desired functionality.**

_Note: The cursor icon not changing when hovering over the header of the specific column is a UI issue that is also present with items on the sidebar._

**Comment by llaske** [comment]
This issue mentioned only local sort. More on https://github.com/llaske/sugarizer-server/issues/50
