### ISSUE TITLE
Server hangs/crashes on when an admin delete its own account

### ISSUE THREAD

**Issue by ahmedkrmn** [llaske/sugarizer-server#82]
When the currently logged in admin user deletes their account, the server hangs and the page is stuck on reload until it crashes.

**Problem:**

![admin logout](https://user-images.githubusercontent.com/20889958/54086757-124f9f80-4355-11e9-82a4-2da548a6198e.gif)

**Fix: #83**

Disallow currently logged in admin from deleting their own account and display an error message.

![delete admin](https://user-images.githubusercontent.com/20889958/54087711-51ceb980-435e-11e9-82b8-63be6fde27c4.gif)

**Comment by llaske** [comment]
It's true but it's a borderline case: the admin remove himself.
Plus we're planning to create a [Teacher profile](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2019.md#improve-sugarizer-server-dashboard) avoid this sort of issue.

**Comment by ahmedkrmn** [comment]
@llaske Shall I close the PR then ?!
I think we can go with the bug fix #83 until we create the teacher profile.

**Comment by llaske** [comment]
No, I've merged your fix. Thanks.
