### ISSUE TITLE
Go to User journal/Launch activity when clicked on chart

### ISSUE THREAD

**Issue by ahmedkrmn** [llaske/sugarizer-server#84]
A nice UX feature can be added which takes the admin to the user journal page when he/she clicks on the user in the _Top Contributors_ chart.

The admin can also launch an activity by clicking on it in the _Top Activities_ chart.

Implemented here: #85

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/85
