### ISSUE TITLE
"Activities successfully updated!" alert showing instead of launching activity

### ISSUE THREAD

**Issue by ahmedkrmn** [llaske/sugarizer-server#87]
When clicking on the launch activity action icon, sometimes instead of opening the activity, the **"Activities successfully updated!"** alert is displayed!

![launch](https://user-images.githubusercontent.com/20889958/54119863-120bde80-43ff-11e9-922f-a33fc93ed616.gif)

**Comment by NikhilM98** [comment]
Looks like you're dragging the activity instead of clicking on the action. Are you using a touch screen or something?

**Comment by ahmedkrmn** [comment]
@NikhilM98 Yeah that was the reason. 
It took me a while to find out it, but I've just submitted a PR with a fix.

**Comment by NikhilM98** [comment]
I really doubt if it's an issue here. I've been using trackpad and mouse and I never faced this issue. This application is supposed to be used by network administrators and teachers. I don't think that they would be confused with such a trivial operation.

**Comment by ahmedkrmn** [comment]
It won't hurt. If I faced it, it means someone else might as well.

**Comment by llaske** [comment]
I'm agree with @NikhilM98. It's not an issue, it's a standard feature on draggable element.

**Comment by ahmedkrmn** [comment]
@llaske I know that this is the expected behavior for a draggable element, but I think that only allowing the dragging action to take place by only dragging through the three dotted icon as shown here #88 would be a nicer idea than dragging anywhere on the row. Plus, nobody would have to face this issue as in the GIF.

**Comment by llaske** [comment]
I must confess that your fix is nice and dragging using three dotted icon is standard in lot of UI.
BTW I'm not fully sure that this update is pertinent.
@tarunsinghal92 could you give us your opinion?

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/88
