### ISSUE TITLE
Cant See Anyone in the Neighbourhood View 

### ISSUE THREAD

**Issue by amanharitsh123** [llaske/sugarizer-server#9]
I have deployed a local server using the classical installation. I have logged on to the server using two different machines on my local network, but I cant see the other newly logged in user in my neighbourhood view until I reload the page

**Comment by llaske** [comment]
Could you detail the way you connect your machines to the server? Is it using Web App (http://localhost:8080) or is it using Client App (file://...) ? Do you have any message in the browser console? Do you see the connection happen on the server log (standard output) ?

**Comment by amanharitsh123** [comment]
I was using Web App(192.168.0.104) to connect my machines

**Comment by llaske** [comment]
Are you sure you've cloned the [dev](https://github.com/llaske/Sugarizer/tree/dev) branch of Sugarizer Client? Could you check the version number in your web app: My settings/About my computer/Sugarizer?

**Comment by amanharitsh123** [comment]
I think thats the error, i didnt  clone the dev branch
