### ISSUE TITLE
Real time search instead of highlighting

### ISSUE THREAD

**Issue by ahmedkrmn** [llaske/sugarizer-server#91]
To search the activities page, admin must click the search button to highlight all occurrences of the word. 

![real timesss](https://user-images.githubusercontent.com/20889958/54125778-9e71cd80-440e-11e9-9097-bf442a594003.gif)

---

I think real time searching would give a better UX. 

![real times](https://user-images.githubusercontent.com/20889958/54125784-a16cbe00-440e-11e9-8427-8e48729f1bab.gif)

@llaske and @tarunsinghal92 What do you think ?!

**Comment by llaske** [comment]
The list of activities is very small. Plus, we choose to not have real time - for pagination reason - for other screens so I don't think we need this.
