### ISSUE TITLE
Statistics page shows all users as inactive

### ISSUE THREAD

**Issue by ahmedkrmn** [llaske/sugarizer-server#95]
The **How many users actives during last month?** chart on the _statistics_ page shows that all users were inactive during last months even though they were!

![inactive](https://user-images.githubusercontent.com/20889958/54251820-34157600-4551-11e9-938b-cd9ac9000667.gif)

Fixed here: #97

**Comment by llaske** [comment]
Oooch, very important issue. Thanks.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/pull/97
