### ISSUE TITLE
Add quick "add all" / "remove all" students from a class

### ISSUE THREAD

**Issue by ahmedkrmn** [llaske/sugarizer-server#98]
Currently, the admin has to go through all the class students one by one to remove them from the class. Same goes for addition.

![class](https://user-images.githubusercontent.com/20889958/54253908-13055300-455a-11e9-9ead-ef93115cb116.gif)

This would be troublesome if there are lots of students in the DB and the admin wants to create a class with all the students except a selected few.

@llaske and @tarunsinghal92 if you think it's nice feature, I can add a PR.

**Comment by llaske** [comment]
I don't think we need this. Classrooms are by definition small and, at worse, the teacher could just remove the classroom itself.
